import {
  DATA_SOURCE as GENERATED_DATA_SOURCE,
  INDUSTRY_CHAIN as GENERATED_INDUSTRY_CHAIN,
} from "./generatedIndustryData.js";
import {
  NEWS as GENERATED_NEWS,
  NEWS_WIRE_DATA_SOURCE as GENERATED_NEWS_WIRE_DATA_SOURCE,
} from "./generatedNewsWire.js";
import {
  KEY_METRIC_DATA,
  KEY_METRIC_DATA_SOURCE,
} from "./generatedKeyMetricData.js";
export {
  NEWS_WIRE_PHASE,
  NEWS_WIRE_PROCESSING_POLICY,
  NEWS_WIRE_RETENTION_DAYS,
  NEWS_WIRE_SEC_EDGAR_WATCHLIST,
  NEWS_WIRE_SOURCES,
  NEWS_WIRE_SOURCE_IDS,
  NEWS_WIRE_STORAGE_POLICY,
} from "./newsWireSources.js";

export const INDUSTRY_CHAIN = GENERATED_INDUSTRY_CHAIN;
export const DATA_SOURCE = GENERATED_DATA_SOURCE;
export const NEWS = GENERATED_NEWS;
export const NEWS_WIRE_DATA_SOURCE = GENERATED_NEWS_WIRE_DATA_SOURCE;
export { KEY_METRIC_DATA, KEY_METRIC_DATA_SOURCE };

// ============ KEY METRICS ============
// The second dashboard section tracks signal definitions and source hygiene.
// Real values should be attached later by source adapters, not hard-coded here.
export const KEY_METRIC_GROUPS = [
  {
    id: "demand",
    title: "需求体感",
    titleEn: "需求信号",
    subtitle: "前端限流、API 价格、模型使用份额，判断需求是否挤压可用算力。",
    metricIds: [
      "closed_model_limits",
      "api_effective_price",
      "token_usage_proxy",
      "open_source_adoption",
    ],
  },
  {
    id: "supply",
    title: "供给约束",
    titleEn: "供给瓶颈",
    subtitle: "GPU、服务器 CPU、HBM/封装/网络、电力与机房，定位真正卡在哪里。",
    metricIds: [
      "gpu_cloud_availability",
      "server_cpu",
      "hbm_packaging_network",
      "datacenter_power",
    ],
  },
  {
    id: "capex",
    title: "扩产投入",
    titleEn: "扩产与消化",
    subtitle: "资本开支与需求吸收配对看，避免只看到花钱看不到消化。",
    metricIds: ["ai_infra_capex", "ai_cloud_backlog"],
  },
  {
    id: "capture",
    title: "价值捕获",
    titleEn: "价值捕获",
    subtitle: "把算力紧缺转成收入、毛利、订单和估值弹性的公司池。",
    metricIds: ["value_capture"],
  },
];

export const KEY_METRICS = [
  {
    id: "closed_model_limits",
    group: "demand",
    category: "模型",
    priority: "P0",
    signalType: "高频事件",
    frequency: "日更 / 事件触发",
    sourceGrade: "B",
    title: "闭源模型配额 / 限流变化",
    titleEn: "闭源模型使用限制",
    definition: "跟踪 ChatGPT、Claude 等头部产品的小时配额、周配额、队列、临时限流和工具单独限额。",
    watch: ["额度更严或排队增加", "旗舰模型从宽松转向分层配额", "高价值工具被单独限额"],
    sources: [
      { label: "OpenAI Help", url: "https://help.openai.com/en/articles/6950777-what-is-chatgpt-plus%3F.eps" },
      { label: "OpenAI Models & Limits", url: "https://help.openai.com/en/articles/11909943-gpt-53-and-gpt-55-in-chatgpt" },
      { label: "Claude Usage Limits", url: "https://support.claude.com/en/articles/9797557-usage-limit-best-practices" },
    ],
    guardrail: "只能作为体感哨兵；配额也可能来自商业分层、风控或产品策略。",
  },
  {
    id: "api_effective_price",
    group: "demand",
    category: "模型",
    priority: "P0",
    signalType: "可抓取价格",
    frequency: "周更 / 变更触发",
    sourceGrade: "A",
    title: "闭源模型 API 有效价格",
    titleEn: "API 实际价格",
    definition: "跟踪 input、output、cached、batch、priority、tool/search 附加费，计算真实 token 成本。",
    watch: ["旗舰模型涨价或降折扣", "缓存/批处理折扣收窄", "推理型模型输出价格上移"],
    sources: [
      { label: "OpenAI Pricing", url: "https://openai.com/api/pricing/" },
      { label: "Anthropic Pricing", url: "https://platform.claude.com/docs/en/about-claude/pricing" },
      { label: "Gemini Pricing", url: "https://ai.google.dev/gemini-api/docs/pricing" },
      { label: "DeepSeek Pricing", url: "https://api-docs.deepseek.com/quick_start/pricing/" },
    ],
    guardrail: "不要只看名义单价；折扣结构变化经常比 headline price 更重要。",
  },
  {
    id: "token_usage_proxy",
    group: "demand",
    category: "模型",
    priority: "P1",
    signalType: "使用代理",
    frequency: "周更 / 季更",
    sourceGrade: "B+",
    title: "平台级 token 使用代理 / 份额变化",
    titleEn: "Token 使用代理指标",
    definition: "用开放平台份额、企业披露的 tokens processed、云侧 AI 使用强度替代不可得的全球 API 调用量。",
    watch: ["OpenRouter 份额变化", "大厂 tokens processed 披露", "模型路由从闭源转向低价或开源"],
    sources: [
      { label: "OpenRouter Rankings", url: "https://openrouter.ai/rankings" },
      { label: "Microsoft IR", url: "https://www.microsoft.com/en-us/investor" },
      { label: "Alphabet IR", url: "https://abc.xyz/investor/" },
    ],
    guardrail: "不要写成全球日调用量；这里是 proxy，不是全市场真实总量。",
  },
  {
    id: "open_source_adoption",
    group: "demand",
    category: "模型",
    priority: "P1",
    signalType: "生态代理",
    frequency: "周更",
    sourceGrade: "B",
    title: "开源模型 adoption proxy",
    titleEn: "开源模型采用情况",
    definition: "跟踪 Hugging Face 下载、衍生模型、开放模型平台份额和主要开源模型官方披露。",
    watch: ["Qwen/Llama/DeepSeek 下载与衍生数", "开放模型在路由平台占比", "闭源 API 需求被开源分流"],
    sources: [
      { label: "Hugging Face Hub", url: "https://huggingface.co/docs/hub/main/en/index" },
      { label: "Hugging Face Models", url: "https://huggingface.co/docs/hub/models" },
      { label: "OpenRouter Rankings", url: "https://openrouter.ai/rankings" },
    ],
    guardrail: "下载量不是调用量；它衡量采用热度和替代速度，不衡量绝对算力消耗。",
  },
  {
    id: "gpu_cloud_availability",
    group: "supply",
    category: "算力",
    priority: "P0",
    signalType: "价格 + 可得性",
    frequency: "日更 / 周更",
    sourceGrade: "A-",
    title: "GPU 云租赁价格 + 可得性 + lead time",
    titleEn: "GPU 云租赁价格与可得性",
    definition: "跟踪 H200、B200/GB200 的 on-demand、reserved、spot、区域差异、最低承诺和 waitlist。",
    watch: ["单位 GPU 小时价格", "有价无货或起租门槛", "新一代集群交付周期"],
    sources: [
      { label: "CoreWeave Pricing", url: "https://docs.coreweave.com/docs/pricing/pricing-instances" },
      { label: "Lambda GPU Cloud", url: "https://lambda.ai/service/gpu-cloud/pricing" },
      { label: "Nebius H200", url: "https://nebius.com/h200" },
    ],
    guardrail: "单一报价不能代表市场；必须分 on-demand、reserved、spot 和区域。",
  },
  {
    id: "server_cpu",
    group: "supply",
    category: "算力",
    priority: "P1",
    signalType: "财报 + 架构迁移",
    frequency: "季更 / 事件触发",
    sourceGrade: "A-",
    title: "服务器 CPU 数据",
    titleEn: "服务器 CPU 信号",
    definition: "单列跟踪通用云与推理基础设施里的 CPU 需求、x86/Arm/custom 份额迁移和实例供给扩张。",
    watch: ["AMD 数据中心 / EPYC", "Intel DCAI / Xeon", "AWS Graviton、Google Axion、Azure Cobalt、阿里云倚天"],
    sources: [
      { label: "AMD IR", url: "https://ir.amd.com/news-events/press-releases" },
      { label: "Intel IR", url: "https://www.intc.com/news-events/press-releases" },
      { label: "AWS Graviton", url: "https://aws.amazon.com/ec2/graviton/" },
      { label: "Google Axion", url: "https://cloud.google.com/products/compute/axion" },
      { label: "Azure Cobalt", url: "https://azure.microsoft.com/en-us/blog/azure-cobalt-100-based-virtual-machines-are-now-generally-available/" },
    ],
    guardrail: "不要做成 CPU 现货价；更重要的是装机结构、attach、实例扩张和价值捕获。",
  },
  {
    id: "hbm_packaging_network",
    group: "supply",
    category: "半导体",
    priority: "P0",
    signalType: "供给瓶颈",
    frequency: "月更 / 季更",
    sourceGrade: "B+",
    title: "HBM / 先进封装 / AI 网络器件供给",
    titleEn: "HBM、封装与 AI 网络",
    definition: "跟踪 GPU 之外的硬约束：HBM、CoWoS/先进封装、800G/1.6T 光模块、AI 交换与互连。",
    watch: ["HBM sold-out 与 ASP", "先进封装扩产节奏", "AI networking 收入和订单"],
    sources: [
      { label: "Micron IR", url: "https://investors.micron.com/latest-news" },
      { label: "TSMC IR", url: "https://investor.tsmc.com/english" },
      { label: "Broadcom IR", url: "https://investors.broadcom.com/" },
      { label: "Marvell IR", url: "https://investor.marvell.com/" },
    ],
    guardrail: "精确产能经常不可得；用官方收入、订单、sold-out 表述和扩产节奏交叉验证。",
  },
  {
    id: "datacenter_power",
    group: "supply",
    category: "电力",
    priority: "P0",
    signalType: "物理约束",
    frequency: "月更 / 季更",
    sourceGrade: "A-",
    title: "数据中心 vacancy / pre-lease / 并网排队 / 电价",
    titleEn: "数据中心电力与出租率",
    definition: "跟踪 colocation vacancy、pre-lease、并网周期、PPA/批发电价和数据中心投运延迟。",
    watch: ["核心市场 vacancy 下探", "pre-lease 比例上升", "电力接入成为投运瓶颈"],
    sources: [
      { label: "CBRE Data Centers", url: "https://www.cbre.com/insights/reports/17887575722" },
      { label: "JLL Data Centers", url: "https://www.jll.com/en-ca/insights/market-dynamics/north-america-data-centers" },
      { label: "IEA Data Centers", url: "https://www.iea.org/news/data-centre-electricity-use-surged-in-2025-even-with-tightening-bottlenecks-driving-a-scramble-for-solutions" },
      { label: "GDS IR", url: "https://investors.gds-services.com/news-releases" },
    ],
    guardrail: "不要写成 AI 数据中心闲置率；公开口径更可靠的是 vacancy、pre-lease 和电力接入。",
  },
  {
    id: "ai_infra_capex",
    group: "capex",
    category: "投资",
    priority: "P0",
    signalType: "财报硬数据",
    frequency: "季更",
    sourceGrade: "A",
    title: "美中头部厂商 AI infra capex + lease + depreciation",
    titleEn: "AI 基础设施资本开支",
    definition: "跟踪美国与中国头部企业的资本开支、finance lease、折旧摊销和 AI 基建投资指引。",
    watch: ["capex 总量与同比", "finance lease 增速", "折旧压力和投运节奏"],
    sources: [
      { label: "Microsoft IR", url: "https://www.microsoft.com/en-us/investor" },
      { label: "Alphabet IR", url: "https://abc.xyz/investor/" },
      { label: "Meta IR", url: "https://investor.atmeta.com/" },
      { label: "Amazon IR", url: "https://ir.aboutamazon.com/" },
      { label: "Alibaba IR", url: "https://home.alibabagroup.com/en-US/ir-home" },
      { label: "Tencent IR", url: "https://www.tencent.com/en-us/investors.html" },
      { label: "Baidu IR", url: "https://ir.baidu.com/" },
    ],
    guardrail: "只看 capex 会误判；必须和租赁、折旧、投运与 backlog 配对。",
  },
  {
    id: "ai_cloud_backlog",
    group: "capex",
    category: "云",
    priority: "P0",
    signalType: "需求吸收",
    frequency: "季更",
    sourceGrade: "A-",
    title: "AI 云 backlog / AI 收入 / tokens processed",
    titleEn: "AI 云需求消化",
    definition: "用云订单、AI 收入、剩余履约义务和 tokens processed 验证资本开支是否被真实需求消化。",
    watch: ["AI 云收入贡献", "backlog / RPO 上修", "tokens processed 与客户数披露"],
    sources: [
      { label: "Microsoft IR", url: "https://www.microsoft.com/en-us/investor" },
      { label: "Alphabet IR", url: "https://abc.xyz/investor/" },
      { label: "Amazon IR", url: "https://ir.aboutamazon.com/" },
      { label: "Baidu IR", url: "https://ir.baidu.com/" },
    ],
    guardrail: "这是 capex 的验证项；没有需求吸收，扩产只是资本强度上升。",
  },
  {
    id: "value_capture",
    group: "capture",
    category: "投资",
    priority: "P0",
    signalType: "利润传导",
    frequency: "季更 / 事件触发",
    sourceGrade: "B+",
    title: "上下游价值捕获与利润率变化",
    titleEn: "价值捕获与利润率传导",
    definition: "跟踪哪些环节把算力紧缺转成收入、毛利率、订单、预收款和估值弹性。",
    watch: ["GPU 云租赁商利用率和毛利", "HBM/网络/液冷/电力设备 backlog", "IDC 租金、预租和回报率"],
    sources: [
      { label: "Micron IR", url: "https://investors.micron.com/latest-news" },
      { label: "Broadcom IR", url: "https://investors.broadcom.com/" },
      { label: "GDS IR", url: "https://investors.gds-services.com/news-releases" },
      { label: "CBRE Data Centers", url: "https://www.cbre.com/insights/reports/17887575722" },
    ],
    guardrail: "紧缺不等于投资收益；最后要落到谁拿租金、谁扩毛利、谁承担折旧。",
  },
];
