export const KEY_METRIC_DATA_SOURCE = {
  status: "verified-snapshot",
  generatedAt: "2026-05-01T00:00:00+08:00",
  coverage: {
    verified: 4,
    total: 11,
  },
  note: "First validation batch: API pricing, GPU cloud pricing, AI infra capex, and server CPU signals.",
};

export const KEY_METRIC_DATA = {
  api_effective_price: {
    status: "verified",
    updatedAt: "2026-05-01",
    cadence: "pricing-page refresh",
    headline: {
      label: "Frontier output price spread",
      value: "107x",
      subvalue: "$30.00 vs $0.28 per 1M output tokens",
      tone: "neutral",
    },
    delta: {
      label: "Batch discount remains structurally important",
      value: "50%",
      tone: "neutral",
    },
    chart: {
      type: "bar",
      title: "Output price by model",
      unit: "$/1M output tokens",
      items: [
        { label: "OpenAI GPT-5.5", value: 30, displayValue: "$30.00", tone: "high" },
        { label: "Claude Opus 4.6", value: 25, displayValue: "$25.00", tone: "high" },
        { label: "Claude Sonnet 4.6", value: 15, displayValue: "$15.00", tone: "mid" },
        { label: "Gemini 3.1 Pro", value: 12, displayValue: "$12.00", tone: "mid" },
        { label: "Claude Haiku 4.5", value: 5, displayValue: "$5.00", tone: "low" },
        { label: "Gemini 3.1 Flash-Lite", value: 1.5, displayValue: "$1.50", tone: "low" },
        { label: "DeepSeek V4 Pro promo", value: 0.87, displayValue: "$0.87", tone: "low" },
        { label: "DeepSeek V4 Flash", value: 0.28, displayValue: "$0.28", tone: "low" },
      ],
    },
    rows: [
      { label: "OpenAI GPT-5.5", value: "$5.00 in / $0.50 cached / $30.00 out" },
      { label: "Claude Opus 4.6", value: "$5.00 in / $0.50 cache hit / $25.00 out" },
      { label: "Gemini 3.1 Pro", value: "$2.00 in / $12.00 out, standard <=200k" },
      { label: "DeepSeek V4 Pro", value: "$0.435 in / $0.003625 cache hit / $0.87 out, promo through 2026-05-31" },
    ],
    sourceNote: "Cross-sectional public list prices; not yet a historical time series.",
    sources: [
      { label: "OpenAI Pricing", url: "https://openai.com/api/pricing/" },
      { label: "Anthropic Pricing", url: "https://platform.claude.com/docs/en/docs/about-claude/pricing" },
      { label: "Gemini Pricing", url: "https://ai.google.dev/gemini-api/docs/pricing" },
      { label: "DeepSeek Pricing", url: "https://api-docs.deepseek.com/quick_start/pricing" },
    ],
  },
  gpu_cloud_availability: {
    status: "verified",
    updatedAt: "2026-05-01",
    cadence: "provider-page refresh",
    headline: {
      label: "Public H200 quotes",
      value: "$3.50-$6.31",
      subvalue: "per GPU-hour, Nebius to CoreWeave",
      tone: "up",
    },
    delta: {
      label: "Public B200 quote range",
      value: "$5.50-$8.60",
      tone: "up",
    },
    chart: {
      type: "bar",
      title: "Public GPU cloud price quotes",
      unit: "$/GPU-hour",
      items: [
        { label: "CoreWeave B200", value: 8.6, displayValue: "$8.60", tone: "high" },
        { label: "Lambda B200", value: 6.69, displayValue: "$6.69", tone: "mid" },
        { label: "CoreWeave H200", value: 6.31, displayValue: "$6.31", tone: "mid" },
        { label: "CoreWeave H100", value: 6.16, displayValue: "$6.16", tone: "mid" },
        { label: "Nebius B200", value: 5.5, displayValue: "$5.50", tone: "mid" },
        { label: "Lambda H100", value: 3.99, displayValue: "$3.99", tone: "low" },
        { label: "Nebius H200", value: 3.5, displayValue: "$3.50", tone: "low" },
        { label: "Nebius H100", value: 2.95, displayValue: "$2.95", tone: "low" },
      ],
    },
    rows: [
      { label: "CoreWeave", value: "HGX B200 $68.80/hour per 8 GPUs; H200 $50.44/hour per 8 GPUs" },
      { label: "Lambda", value: "B200 $6.69/GPU-hour; H100 $3.99/GPU-hour for 8x instances" },
      { label: "Nebius", value: "B200 $5.50/GPU-hour; H200 $3.50/GPU-hour; H100 $2.95/GPU-hour" },
    ],
    sourceNote: "Availability, minimum term, region, and cluster size differ by provider; prices are not a pure like-for-like market index.",
    sources: [
      { label: "CoreWeave Pricing", url: "https://www.coreweave.com/pricing" },
      { label: "Lambda Pricing", url: "https://lambda.ai/pricing" },
      { label: "Nebius Pricing", url: "https://nebius.com/prices" },
    ],
  },
  ai_infra_capex: {
    status: "verified",
    updatedAt: "2026-05-01",
    cadence: "quarterly filings",
    headline: {
      label: "Latest quarter gross capex proxy",
      value: "$130.6B",
      subvalue: "MSFT + Alphabet + Amazon + Meta",
      tone: "up",
    },
    delta: {
      label: "YoY comparable growth",
      value: "+80%",
      tone: "up",
    },
    chart: {
      type: "bar",
      title: "Latest quarter vs prior-year comparable",
      unit: "$B",
      items: [
        { label: "Amazon Q1 2026", value: 44.203, displayValue: "$44.2B", previousValue: 25.019, previousDisplayValue: "$25.0B", tone: "high" },
        { label: "Alphabet Q1 2026", value: 35.674, displayValue: "$35.7B", previousValue: 17.197, previousDisplayValue: "$17.2B", tone: "high" },
        { label: "Microsoft FY26 Q3", value: 30.876, displayValue: "$30.9B", previousValue: 16.745, previousDisplayValue: "$16.7B", tone: "high" },
        { label: "Meta Q1 2026", value: 19.84, displayValue: "$19.8B", previousValue: 13.692, previousDisplayValue: "$13.7B", tone: "mid" },
      ],
    },
    rows: [
      { label: "Amazon", value: "Purchases of PP&E $44.203B; TTM net PP&E spend +67% YoY, primarily AI" },
      { label: "Alphabet", value: "Purchases of PP&E $35.674B; Google Cloud revenue +63% YoY" },
      { label: "Microsoft", value: "Additions to property and equipment $30.876B; AI infrastructure pressured cloud gross margin" },
      { label: "Meta", value: "Capex incl. finance leases $19.840B; 2026 guide raised to $125B-$145B" },
    ],
    sourceNote: "Metric intentionally mixes fiscal calendars. Meta includes finance-lease principal payments; the other bars use purchases/additions to PP&E.",
    sources: [
      { label: "Microsoft FY26 Q3 Cash Flows", url: "https://www.microsoft.com/en-us/investor/earnings/fy-2026-q3/cash-flows" },
      { label: "Alphabet Q1 2026 SEC Exhibit", url: "https://www.sec.gov/Archives/edgar/data/1652044/000165204426000043/googexhibit991q12026.htm" },
      { label: "Amazon Q1 2026 Results", url: "https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-First-Quarter-Results/default.aspx" },
      { label: "Meta Q1 2026 Results", url: "https://investor.atmeta.com/investor-news/press-release-details/2026/Meta-Reports-First-Quarter-2026-Results/default.aspx" },
    ],
  },
  server_cpu: {
    status: "mixed-proxy",
    updatedAt: "2026-05-01",
    cadence: "quarterly + event-driven",
    headline: {
      label: "CPU demand signal",
      value: "strong",
      subvalue: "Intel DCAI +22%; AMD DC +39%; AWS Graviton cores scaling",
      tone: "up",
    },
    delta: {
      label: "AWS chip business run-rate",
      value: ">$20B",
      tone: "up",
    },
    chart: {
      type: "bar",
      title: "Latest disclosed CPU-related proxies",
      unit: "$B / signal",
      items: [
        { label: "AWS chips run-rate", value: 20, displayValue: ">$20B", tone: "high" },
        { label: "AMD Data Center", value: 5.4, displayValue: "$5.4B", tone: "mid" },
        { label: "Intel DCAI", value: 5.1, displayValue: "$5.1B", tone: "mid" },
      ],
    },
    events: [
      { date: "2026-04-24", label: "Meta starts deploying tens of millions of AWS Graviton cores for agentic AI workloads." },
      { date: "2026-04-23", label: "Intel reports DCAI revenue of $5.1B, up 22% YoY." },
      { date: "2026-02-03", label: "AMD reports Q4 Data Center revenue of $5.4B, up 39% YoY; Q1 2026 report is scheduled after May 1." },
    ],
    rows: [
      { label: "Intel DCAI", value: "$5.1B Q1 2026 revenue, +22% YoY" },
      { label: "AMD Data Center", value: "$5.4B Q4 2025 revenue, +39% YoY, driven by EPYC and Instinct" },
      { label: "AWS Graviton", value: "Meta deployment starts with tens of millions of Graviton cores" },
      { label: "AWS chips", value: "> $20B annual revenue run-rate, includes Graviton, Trainium, and Nitro" },
    ],
    sourceNote: "Not a pure CPU revenue index: AMD Data Center includes GPUs, and AWS chips include Trainium/Nitro. This is a demand-proxy card until cleaner CPU-only disclosures are available.",
    sources: [
      { label: "Intel Q1 2026 Results", url: "https://www.intc.com/news-events/press-releases/detail/1767/intel-reports-first-quarter-2026-financial-results" },
      { label: "AMD Q4 2025 Results", url: "https://www.amd.com/en/newsroom/press-releases/2026-2-3-amd-reports-fourth-quarter-and-full-year-2025-fina.html" },
      { label: "Amazon Q1 2026 Results", url: "https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-First-Quarter-Results/default.aspx" },
      { label: "AWS Graviton / Meta", url: "https://press.aboutamazon.com/2026/4/meta-signs-agreement-with-aws-to-power-agentic-ai-on-aws-graviton-chips" },
    ],
  },
};
