export const NEWS_WIRE_RETENTION_DAYS = 30;

export const NEWS_WIRE_PHASE = {
  id: "p0-official-facts",
  status: "approved",
  scope: "P0 official and high-signal public factual sources only",
  excludes: [
    "paid media",
    "research/newsletters",
    "Chinese sources",
    "social media",
    "full-text scraping",
  ],
};

export const NEWS_WIRE_STORAGE_POLICY = {
  retentionDays: NEWS_WIRE_RETENTION_DAYS,
  fetchFullText: false,
  allowedRawFields: [
    "title",
    "url",
    "source",
    "sourceId",
    "publishedAt",
    "summary",
    "language",
    "category",
    "fetchedAt",
  ],
  allowedGeneratedFields: [
    "titleZh",
    "summaryZh",
    "severity",
    "tags",
    "layers",
    "impactNote",
    "dedupeKey",
  ],
};

export const NEWS_WIRE_PROCESSING_POLICY = {
  translationSummaryMode: "server_batch",
  translationSummaryReason: "Prefer a server-side or offline batch job because it is easier to cache, retry, dedupe, and keep stable than browser-time generation.",
  summaryInput: "stored_title_link_and_short_snippet_only",
  browserAdapterAccepted: true,
  weakHintSourceIds: ["spacex_updates"],
  edgarWatchlistScope: "ai_private_and_public_companies_only",
};

export const NEWS_WIRE_SEC_EDGAR_WATCHLIST = [
  { name: "CoreWeave", ticker: "CRWV", cik: "0001769628", reason: "AI neocloud filing watch" },
  { name: "NVIDIA", ticker: "NVDA", cik: "0001045810", reason: "AI accelerator leader" },
  { name: "Advanced Micro Devices", ticker: "AMD", cik: "0000002488", reason: "AI accelerator and server CPU supplier" },
  { name: "Microsoft", ticker: "MSFT", cik: "0000789019", reason: "Azure AI and OpenAI ecosystem" },
  { name: "Alphabet", ticker: "GOOGL", cik: "0001652044", reason: "Gemini and AI infrastructure" },
  { name: "Amazon", ticker: "AMZN", cik: "0001018724", reason: "AWS AI infrastructure" },
  { name: "Meta", ticker: "META", cik: "0001326801", reason: "Llama and AI infrastructure" },
  { name: "Tesla", ticker: "TSLA", cik: "0001318605", reason: "Optimus, autonomy, Dojo, and energy infrastructure" },
];

const aiKeywords = [
  "ai",
  "artificial intelligence",
  "agi",
  "agent",
  "model",
  "openai",
  "chatgpt",
  "codex",
  "inference",
  "training",
  "copilot",
  "cloud",
  "data center",
  "datacenter",
  "gpu",
  "chip",
  "robot",
  "robotics",
  "autonomy",
  "fsd",
  "dojo",
  "starlink",
  "infrastructure",
];

export const NEWS_WIRE_SOURCES = [
  {
    id: "openai_news",
    name: "OpenAI News",
    url: "https://openai.com/news/rss.xml",
    sourceType: "official_feed",
    adapter: "rss",
    language: "en",
    primaryCategory: "模型",
    categories: ["模型", "应用", "政策"],
    keywordMode: "include",
    keywords: aiKeywords,
  },
  {
    id: "anthropic_news",
    name: "Anthropic Newsroom",
    url: "https://www.anthropic.com/news",
    sourceType: "official_page",
    adapter: "page",
    language: "en",
    primaryCategory: "模型",
    categories: ["模型", "应用"],
    keywordMode: "include",
    keywords: aiKeywords,
  },
  {
    id: "google_keyword",
    name: "Google The Keyword",
    url: "https://blog.google/feed/",
    sourceType: "official_feed",
    adapter: "rss",
    language: "en",
    primaryCategory: "模型",
    categories: ["模型", "应用", "芯片"],
    keywordMode: "include",
    keywords: aiKeywords,
  },
  {
    id: "google_deepmind",
    name: "Google DeepMind Blog",
    url: "https://deepmind.google/blog/",
    sourceType: "official_page",
    adapter: "page",
    language: "en",
    primaryCategory: "模型",
    categories: ["模型"],
    keywordMode: "include",
    keywords: aiKeywords,
  },
  {
    id: "meta_ai",
    name: "Meta AI Blog",
    url: "https://ai.meta.com/blog/",
    sourceType: "official_page",
    adapter: "page",
    language: "en",
    primaryCategory: "模型",
    categories: ["模型", "应用"],
    keywordMode: "include",
    keywords: aiKeywords,
  },
  {
    id: "microsoft_news",
    name: "Microsoft News",
    url: "https://news.microsoft.com/feed/",
    sourceType: "official_feed",
    adapter: "rss",
    language: "en",
    primaryCategory: "应用",
    categories: ["模型", "应用"],
    keywordMode: "include",
    keywords: aiKeywords,
  },
  {
    id: "nvidia_blog",
    name: "NVIDIA Blog",
    url: "https://blogs.nvidia.com/feed/",
    sourceType: "official_feed",
    adapter: "rss",
    language: "en",
    primaryCategory: "芯片",
    categories: ["芯片", "机器人", "应用"],
    keywordMode: "include",
    keywords: aiKeywords,
  },
  {
    id: "nvidia_developer",
    name: "NVIDIA Developer Blog",
    url: "https://developer.nvidia.com/blog/feed/",
    sourceType: "official_feed",
    adapter: "atom",
    language: "en",
    primaryCategory: "芯片",
    categories: ["芯片", "机器人", "应用"],
    keywordMode: "include",
    keywords: aiKeywords,
  },
  {
    id: "aws_ml_blog",
    name: "AWS Machine Learning Blog",
    url: "https://aws.amazon.com/blogs/machine-learning/feed/",
    sourceType: "official_feed",
    adapter: "rss",
    language: "en",
    primaryCategory: "应用",
    categories: ["模型", "应用"],
    keywordMode: "include",
    keywords: aiKeywords,
  },
  {
    id: "azure_blog",
    name: "Azure Blog",
    url: "https://azure.microsoft.com/en-us/blog/feed/",
    sourceType: "official_feed",
    adapter: "rss",
    language: "en",
    primaryCategory: "应用",
    categories: ["模型", "应用"],
    keywordMode: "include",
    keywords: aiKeywords,
  },
  {
    id: "tesla_blog",
    name: "Tesla Blog",
    url: "https://www.tesla.com/blog",
    sourceType: "official_page",
    adapter: "browser_page",
    language: "en",
    primaryCategory: "机器人",
    categories: ["机器人", "电力", "应用"],
    keywordMode: "include",
    keywords: [
      ...aiKeywords,
      "optimus",
      "robotaxi",
      "autopilot",
      "energy storage",
      "megapack",
      "supercharger",
    ],
    accessNote: "Official page is browser-readable, but direct curl fetch returns 403.",
  },
  {
    id: "spacex_updates",
    name: "SpaceX Updates",
    url: "https://www.spacex.com/updates/",
    sourceType: "official_page",
    adapter: "browser_page",
    language: "en",
    primaryCategory: "应用",
    categories: ["应用"],
    keywordMode: "include",
    keywords: [
      ...aiKeywords,
      "starship",
      "starlink",
      "launch",
      "satellite",
      "raptor",
    ],
    displayStrength: "weak_hint",
    strictKeywordFilter: true,
    accessNote: "Official page is currently blocked for direct curl fetch; use page adapter or manual validation.",
  },
  {
    id: "data_center_dynamics",
    name: "Data Center Dynamics",
    url: "https://www.datacenterdynamics.com/en/rss/",
    sourceType: "industry_feed",
    adapter: "rss",
    language: "en",
    primaryCategory: "电力",
    categories: ["电力", "芯片", "应用"],
    keywordMode: "include",
    keywords: aiKeywords,
  },
  {
    id: "federal_register",
    name: "Federal Register API",
    url: "https://www.federalregister.gov/api/v1/documents.json",
    sourceType: "official_api",
    adapter: "federal_register",
    language: "en",
    primaryCategory: "政策",
    categories: ["政策", "芯片"],
    keywordMode: "query",
    keywords: [
      "artificial intelligence",
      "semiconductor",
      "export control",
      "advanced computing",
      "AI",
    ],
  },
  {
    id: "commerce_press",
    name: "U.S. Commerce Press Releases",
    url: "https://www.commerce.gov/news/press-releases",
    sourceType: "official_page",
    adapter: "page",
    language: "en",
    primaryCategory: "政策",
    categories: ["政策", "芯片"],
    keywordMode: "include",
    keywords: [
      "artificial intelligence",
      "semiconductor",
      "export control",
      "BIS",
      "Entity List",
      "chip",
    ],
  },
  {
    id: "sec_edgar",
    name: "SEC EDGAR API",
    url: "https://data.sec.gov/submissions/",
    sourceType: "official_api",
    adapter: "sec_edgar",
    language: "en",
    primaryCategory: "投资",
    categories: ["投资", "并购"],
    keywordMode: "watchlist",
    watchlistScope: "ai_private_and_public_companies_only",
    keywords: ["S-1", "8-K", "10-K", "10-Q", "acquisition", "merger"],
  },
];

export const NEWS_WIRE_SOURCE_IDS = NEWS_WIRE_SOURCES.map((source) => source.id);
