export const KEY_METRIC_TOTAL = 11;

export const KEY_METRIC_SOURCE_SNAPSHOTS = {
  closed_model_limits: {
    status: "verified",
    updatedAt: "2026-05-01",
    cadence: "官方帮助页事件触发",
    headline: {
      label: "Plus/Business 手动 Thinking 周限额",
      value: "3,000",
      subvalue: "GPT-5.5 Thinking 每周消息数",
      tone: "up",
    },
    delta: {
      label: "Plus/Go GPT-5.3 常规额度",
      value: "160/3h",
      tone: "neutral",
    },
    chart: {
      type: "bar",
      title: "OpenAI 已披露消息额度",
      unit: "消息数",
      items: [
        { label: "GPT-5.5 Thinking 周额度", value: 3000, displayValue: "3,000/周", tone: "high" },
        { label: "Plus/Go GPT-5.3", value: 160, displayValue: "160/3小时", tone: "mid" },
        { label: "Free GPT-5.3", value: 10, displayValue: "10/5小时", tone: "low" },
      ],
    },
    events: [
      { date: "2026-05-01", label: "OpenAI 帮助页显示 GPT-5.5 Thinking 可手动选择，Plus/Business 周额度 3,000 条。" },
      { date: "2026-05-01", label: "Claude 帮助页未披露固定条数，强调五小时会话额度、周额度、模型选择、工具使用和上下文长度共同影响消耗。" },
    ],
    rows: [
      { label: "OpenAI Free", value: "GPT-5.3 每 5 小时 10 条，耗尽后自动切到 mini。" },
      { label: "OpenAI Plus/Go", value: "GPT-5.3 每 3 小时 160 条；Thinking 手动使用有独立规则。" },
      { label: "OpenAI Thinking", value: "Plus/Business 手动选择 GPT-5.5 Thinking 时，每周最多 3,000 条。" },
      { label: "Claude", value: "额度受消息长度、附件、上下文、工具使用和模型选择影响，官方建议在 Usage 设置中查看。" },
    ],
    sourceNote: "这是产品额度哨兵，只反映官方披露的计划规则；实际限流还可能由风控、峰值负载和工作区策略触发。",
    sources: [
      { label: "OpenAI GPT-5.3/5.5 帮助页", url: "https://help.openai.com/en/articles/11909943-gpt-53-and-gpt-55-in-chatgpt" },
      { label: "Claude 使用额度建议", url: "https://support.claude.com/en/articles/9797557-usage-limit-best-practices" },
    ],
  },
  api_effective_price: {
    status: "verified",
    updatedAt: "2026-05-01",
    cadence: "定价页刷新",
    headline: {
      label: "前沿模型输出价格差",
      value: "107x",
      subvalue: "$30.00 对 $0.28 / 百万输出 token",
      tone: "neutral",
    },
    delta: {
      label: "批处理折扣仍然关键",
      value: "50%",
      tone: "neutral",
    },
    chart: {
      type: "bar",
      title: "各模型输出 token 价格",
      unit: "美元/百万输出 token",
      items: [
        { label: "OpenAI GPT-5.5", value: 30, displayValue: "$30.00", tone: "high" },
        { label: "Claude Opus 4.7 / 4.6", value: 25, displayValue: "$25.00", tone: "high" },
        { label: "Claude Sonnet 4.6", value: 15, displayValue: "$15.00", tone: "mid" },
        { label: "Gemini 3.1 Pro", value: 12, displayValue: "$12.00", tone: "mid" },
        { label: "Claude Haiku 4.5", value: 5, displayValue: "$5.00", tone: "low" },
        { label: "Gemini 3.1 Flash-Lite", value: 1.5, displayValue: "$1.50", tone: "low" },
        { label: "DeepSeek V4 Pro 优惠价", value: 0.87, displayValue: "$0.87", tone: "low" },
        { label: "DeepSeek V4 Flash", value: 0.28, displayValue: "$0.28", tone: "low" },
      ],
    },
    rows: [
      { label: "OpenAI GPT-5.5", value: "输入 $5.00 / 缓存 $0.50 / 输出 $30.00" },
      { label: "Claude Opus 4.7 / 4.6", value: "输入 $5.00 / 缓存命中 $0.50 / 输出 $25.00" },
      { label: "Gemini 3.1 Pro", value: "输入 $2.00 / 输出 $12.00，标准上下文 <=200k" },
      { label: "DeepSeek V4 Pro", value: "输入 $0.435 / 缓存命中 $0.003625 / 输出 $0.87，优惠至 2026-05-31" },
    ],
    sourceNote: "这是公开报价的横截面快照，还不是历史时间序列。",
    sources: [
      { label: "OpenAI 定价", url: "https://openai.com/api/pricing/" },
      { label: "Anthropic 定价", url: "https://platform.claude.com/docs/en/docs/about-claude/pricing" },
      { label: "Gemini 定价", url: "https://ai.google.dev/gemini-api/docs/pricing" },
      { label: "DeepSeek 定价", url: "https://api-docs.deepseek.com/quick_start/pricing" },
    ],
  },
  token_usage_proxy: {
    status: "mixed-proxy",
    updatedAt: "2026-05-01",
    cadence: "周度平台排名刷新",
    headline: {
      label: "OpenRouter Top10 周用量",
      value: "约11.1T",
      subvalue: "公开排名页 token 量合计",
      tone: "up",
    },
    delta: {
      label: "Top2 模型周用量",
      value: "约3.7T",
      tone: "up",
    },
    chart: {
      type: "bar",
      title: "OpenRouter 周度 token 排名",
      unit: "万亿 token",
      items: [
        { label: "Kimi K2.6", value: 1.94, displayValue: "1.94T", tone: "high" },
        { label: "Hy3 Preview free", value: 1.78, displayValue: "1.78T", tone: "high" },
        { label: "Claude Sonnet 4.6", value: 1.38, displayValue: "1.38T", tone: "mid" },
        { label: "Claude Opus 4.7", value: 1.05, displayValue: "1.05T", tone: "mid" },
        { label: "DeepSeek V3.2", value: 1.05, displayValue: "1.05T", tone: "mid" },
        { label: "Gemini 3 Flash Preview", value: 0.992, displayValue: "992B", tone: "mid" },
        { label: "Step 3.5 Flash", value: 0.816, displayValue: "816B", tone: "low" },
        { label: "Minimax M2.7", value: 0.724, displayValue: "724B", tone: "low" },
        { label: "Grok 4.1 Fast", value: 0.688, displayValue: "688B", tone: "low" },
        { label: "Nemotron 3 Super free", value: 0.66, displayValue: "660B", tone: "low" },
      ],
    },
    rows: [
      { label: "平台口径", value: "OpenRouter 公开排名基于平台真实用量，不代表全市场 API 调用量。" },
      { label: "集中度", value: "Top10 合计约 11.1T tokens，Top2 合计约 3.7T tokens。" },
      { label: "需求含义", value: "模型路由平台上，低价、开放和中国模型在实际生产流量中占比显著。" },
    ],
    sourceNote: "这是平台代理指标，不是全球 token 使用总量。OpenRouter 用户结构、模型供给和分类页会影响排名。",
    sources: [
      { label: "OpenRouter 排名", url: "https://openrouter.ai/rankings" },
      { label: "OpenRouter 模型 API 文档", url: "https://openrouter.ai/docs/overview/models" },
    ],
  },
  open_source_adoption: {
    status: "mixed-proxy",
    updatedAt: "2026-05-01",
    cadence: "周度生态页刷新",
    headline: {
      label: "Hugging Face 模型库规模",
      value: "217万+",
      subvalue: "公开模型条目数量",
      tone: "up",
    },
    delta: {
      label: "热门开放模型单项下载",
      value: "62.3万",
      tone: "up",
    },
    chart: {
      type: "bar",
      title: "Hugging Face 热门开放模型下载代理",
      unit: "下载量",
      items: [
        { label: "DeepSeek-OCR", value: 623000, displayValue: "623k", tone: "high" },
        { label: "Qwen3-VL-8B", value: 262000, displayValue: "262k", tone: "mid" },
        { label: "Qwen3-VL-4B", value: 165000, displayValue: "165k", tone: "mid" },
        { label: "DeepSeek-V3.2-Exp", value: 93300, displayValue: "93.3k", tone: "low" },
        { label: "GLM-4.6", value: 59500, displayValue: "59.5k", tone: "low" },
        { label: "Qwen3-VL-2B", value: 23800, displayValue: "23.8k", tone: "low" },
      ],
    },
    rows: [
      { label: "Hugging Face", value: "模型库公开条目超过 217 万，热门榜显示 DeepSeek/Qwen/GLM 等模型活跃。" },
      { label: "OpenRouter", value: "Nemotron 3 Super free 周用量约 660B tokens，是开放模型推理需求代理。" },
      { label: "口径边界", value: "下载量衡量开发者采用热度，不等于线上推理调用量。" },
    ],
    sourceNote: "这是生态代理指标。Hugging Face 下载量、模型条目数和 OpenRouter 免费模型用量都不能单独代表真实线上调用。",
    sources: [
      { label: "Hugging Face 模型页", url: "https://huggingface.co/models" },
      { label: "OpenRouter 排名", url: "https://openrouter.ai/rankings" },
    ],
  },
  gpu_cloud_availability: {
    status: "verified",
    updatedAt: "2026-05-01",
    cadence: "云厂商报价页刷新",
    headline: {
      label: "公开 H200 报价",
      value: "$3.50-$6.31",
      subvalue: "每 GPU 小时，Nebius 至 CoreWeave",
      tone: "up",
    },
    delta: {
      label: "公开 B200 报价区间",
      value: "$5.50-$8.60",
      tone: "up",
    },
    chart: {
      type: "bar",
      title: "GPU 云公开报价",
      unit: "美元/GPU 小时",
      items: [
        { label: "CoreWeave B200", value: 8.6, displayValue: "$8.60", tone: "high" },
        { label: "Lambda B200", value: 6.69, displayValue: "$6.69", tone: "mid" },
        { label: "CoreWeave H200", value: 6.31, displayValue: "$6.31", tone: "mid" },
        { label: "CoreWeave H100", value: 6.16, displayValue: "$6.16", tone: "mid" },
        { label: "Nebius B200", value: 5.5, displayValue: "$5.50", tone: "mid" },
        { label: "Lambda H100", value: 3.99, displayValue: "$3.99", tone: "low" },
        { label: "Nebius H200", value: 3.5, displayValue: "$3.50", tone: "low" },
        { label: "Nebius H100", value: 2.95, displayValue: "$2.95", tone: "low" },
      ],
    },
    rows: [
      { label: "CoreWeave", value: "HGX B200 每 8 卡每小时 $68.80；H200 每 8 卡每小时 $50.44" },
      { label: "Lambda", value: "B200 每 GPU 小时 $6.69；8 卡 H100 每 GPU 小时 $3.99" },
      { label: "Nebius", value: "B200 每 GPU 小时 $5.50；H200 $3.50；H100 $2.95" },
    ],
    sourceNote: "不同厂商的可得性、最低租期、区域和集群规模不同；这些报价不能直接当成完全可比的市场指数。",
    sources: [
      { label: "CoreWeave 定价", url: "https://www.coreweave.com/pricing" },
      { label: "Lambda 定价", url: "https://lambda.ai/pricing" },
      { label: "Nebius 定价", url: "https://nebius.com/prices" },
    ],
  },
  ai_infra_capex: {
    status: "verified",
    updatedAt: "2026-05-01",
    cadence: "季度财报",
    headline: {
      label: "最近季度总资本开支代理值",
      value: "$130.6B",
      subvalue: "MSFT + Alphabet + Amazon + Meta",
      tone: "up",
    },
    delta: {
      label: "可比口径同比增长",
      value: "+80%",
      tone: "up",
    },
    chart: {
      type: "bar",
      title: "最近季度与去年同期对比",
      unit: "十亿美元",
      items: [
        { label: "Amazon Q1 2026", value: 44.203, displayValue: "$44.2B", previousValue: 25.019, previousDisplayValue: "$25.0B", tone: "high" },
        { label: "Alphabet Q1 2026", value: 35.674, displayValue: "$35.7B", previousValue: 17.197, previousDisplayValue: "$17.2B", tone: "high" },
        { label: "Microsoft FY26 Q3", value: 30.876, displayValue: "$30.9B", previousValue: 16.745, previousDisplayValue: "$16.7B", tone: "high" },
        { label: "Meta Q1 2026", value: 19.84, displayValue: "$19.8B", previousValue: 13.692, previousDisplayValue: "$13.7B", tone: "mid" },
      ],
    },
    rows: [
      { label: "Amazon", value: "购买 PP&E $44.203B；过去 12 个月净 PP&E 支出同比 +67%，主要来自 AI" },
      { label: "Alphabet", value: "购买 PP&E $35.674B；Google Cloud 收入同比 +63%" },
      { label: "Microsoft", value: "新增物业与设备 $30.876B；AI 基础设施压低云业务毛利率" },
      { label: "Meta", value: "资本开支含融资租赁 $19.840B；2026 指引上调至 $125B-$145B" },
    ],
    sourceNote: "这个指标有意混合不同公司财年日历。Meta 包含融资租赁本金支付；其余柱状值使用购买或新增 PP&E。",
    sources: [
      { label: "Microsoft FY26 Q3 现金流", url: "https://www.microsoft.com/en-us/investor/earnings/fy-2026-q3/cash-flows" },
      { label: "Alphabet Q1 2026 SEC 附件", url: "https://www.sec.gov/Archives/edgar/data/1652044/000165204426000043/googexhibit991q12026.htm" },
      { label: "Amazon Q1 2026 业绩", url: "https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-First-Quarter-Results/default.aspx" },
      { label: "Meta Q1 2026 业绩", url: "https://investor.atmeta.com/investor-news/press-release-details/2026/Meta-Reports-First-Quarter-2026-Results/default.aspx" },
    ],
  },
  server_cpu: {
    status: "mixed-proxy",
    updatedAt: "2026-05-01",
    cadence: "季度 + 事件触发",
    headline: {
      label: "CPU 需求信号",
      value: "偏强",
      subvalue: "Intel DCAI +22%；AMD 数据中心 +39%；AWS Graviton 核心数扩张",
      tone: "up",
    },
    delta: {
      label: "AWS 芯片业务年化收入",
      value: ">$20B",
      tone: "up",
    },
    chart: {
      type: "bar",
      title: "最新披露的 CPU 相关代理指标",
      unit: "十亿美元 / 信号",
      items: [
        { label: "AWS 芯片年化收入", value: 20, displayValue: ">$20B", tone: "high" },
        { label: "AMD 数据中心", value: 5.4, displayValue: "$5.4B", tone: "mid" },
        { label: "Intel DCAI", value: 5.1, displayValue: "$5.1B", tone: "mid" },
      ],
    },
    events: [
      { date: "2026-04-24", label: "Meta 开始部署数千万个 AWS Graviton 核心，用于智能体 AI 工作负载。" },
      { date: "2026-04-23", label: "Intel 披露 DCAI 收入 $5.1B，同比增长 22%。" },
      { date: "2026-02-03", label: "AMD 披露 Q4 数据中心收入 $5.4B，同比增长 39%；Q1 2026 财报安排在 5 月 1 日之后。" },
    ],
    rows: [
      { label: "Intel DCAI", value: "Q1 2026 收入 $5.1B，同比 +22%" },
      { label: "AMD 数据中心", value: "Q4 2025 收入 $5.4B，同比 +39%，由 EPYC 和 Instinct 推动" },
      { label: "AWS Graviton", value: "Meta 部署从数千万个 Graviton 核心开始" },
      { label: "AWS 芯片", value: "年化收入 >$20B，包含 Graviton、Trainium 和 Nitro" },
    ],
    sourceNote: "这不是纯 CPU 收入指数：AMD 数据中心收入包含 GPU，AWS 芯片收入也包含 Trainium/Nitro。在更干净的纯 CPU 披露出现前，只能作为需求代理卡片。",
    sources: [
      { label: "Intel Q1 2026 业绩", url: "https://www.intc.com/news-events/press-releases/detail/1767/intel-reports-first-quarter-2026-financial-results" },
      { label: "AMD Q4 2025 业绩", url: "https://www.amd.com/en/newsroom/press-releases/2026-2-3-amd-reports-fourth-quarter-and-full-year-2025-fina.html" },
      { label: "Amazon Q1 2026 业绩", url: "https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-First-Quarter-Results/default.aspx" },
      { label: "AWS Graviton / Meta", url: "https://press.aboutamazon.com/2026/4/meta-signs-agreement-with-aws-to-power-agentic-ai-on-aws-graviton-chips" },
    ],
  },
  hbm_packaging_network: {
    status: "mixed-proxy",
    updatedAt: "2026-05-01",
    cadence: "季度财报 + 事件触发",
    headline: {
      label: "Micron FY26 Q2 收入",
      value: "$23.86B",
      subvalue: "AI 内存需求驱动的公司级收入代理",
      tone: "up",
    },
    delta: {
      label: "Broadcom AI 半导体指引",
      value: "$8.2B",
      tone: "up",
    },
    chart: {
      type: "bar",
      title: "HBM / AI 网络 / 数据中心代理收入",
      unit: "十亿美元",
      items: [
        { label: "Micron FY26 Q2 收入", value: 23.86, displayValue: "$23.86B", tone: "high" },
        { label: "Broadcom Q1 FY26 AI 半导体指引", value: 8.2, displayValue: "$8.2B", tone: "high" },
        { label: "Marvell FY26 Q4 数据中心", value: 1.651, displayValue: "$1.65B", tone: "mid" },
      ],
    },
    rows: [
      { label: "Micron", value: "FY26 Q2 收入 $23.86B，管理层称 AI 时代内存战略价值推动创纪录结果。" },
      { label: "Broadcom", value: "Q4 FY25 AI 半导体收入同比 +74%；Q1 FY26 AI 半导体收入指引 $8.2B。" },
      { label: "Marvell", value: "FY26 Q4 数据中心收入 $1.651B，同比增长 21%，占季度收入 74%。" },
      { label: "TSMC", value: "先进封装/CoWoS 仍是交叉验证来源，但此卡当前未填入可直接比较的产能数。" },
    ],
    sourceNote: "这是供给瓶颈代理卡，不是纯 HBM 或 CoWoS 产能指数。Micron 是公司级收入，Broadcom 是 AI 半导体，Marvell 是数据中心口径。",
    sources: [
      { label: "Micron FY26 Q2 业绩", url: "https://investors.micron.com/news-releases/news-release-details/micron-technology-inc-reports-results-second-quarter-fiscal-2026" },
      { label: "Broadcom FY25 Q4 业绩", url: "https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-fourth-quarter-and-fiscal-year-2025" },
      { label: "Marvell FY26 Q4 业绩", url: "https://investor.marvell.com/news-events/press-releases/detail/1011/marvell-technology-inc-reports-fourth-quarter-and-fiscal-year-2026-financial-results" },
      { label: "TSMC 投资者关系", url: "https://investor.tsmc.com/english" },
    ],
  },
  datacenter_power: {
    status: "mixed-proxy",
    updatedAt: "2026-05-01",
    cadence: "月度/季度报告刷新",
    headline: {
      label: "北美数据中心空置率",
      value: "1%",
      subvalue: "JLL 年末 2025 报告",
      tone: "up",
    },
    delta: {
      label: "IEA 2025 数据中心用电增长",
      value: "+17%",
      tone: "up",
    },
    chart: {
      type: "events",
      events: [
        { date: "2026-02-17", label: "JLL 披露北美数据中心空置率连续第二年处于 1% 的历史低位。" },
        { date: "2026-02-17", label: "JLL 披露 35GW 在建管线中，64% 位于传统成熟市场之外。" },
        { date: "2026-04-16", label: "IEA 披露 2025 年数据中心用电增长 17%，AI 数据中心增长更快。" },
        { date: "2026-04-16", label: "IEA 披露科技行业占 2025 年企业可再生能源 PPA 签约约 40%。" },
      ],
    },
    rows: [
      { label: "JLL vacancy", value: "北美数据中心空置率 1%，供给紧张仍未缓解。" },
      { label: "JLL pipeline", value: "35GW 在建管线，64% 转向传统核心市场外。" },
      { label: "IEA demand", value: "2025 年数据中心用电 +17%；到 2030 年数据中心用电预计翻倍。" },
      { label: "CBRE", value: "2026 展望强调电力成本和 36 个月内交付 300MW+ 已超过纯连接性成为选址核心。" },
    ],
    sourceNote: "这是电力/机房约束代理。JLL 的 vacancy、IEA 的用电增长和 CBRE 的选址判断口径不同，不能相加成一个单一指数。",
    sources: [
      { label: "JLL 北美数据中心报告", url: "https://www.jll.com/en-us/newsroom/jll-north-america-data-center-report-year-end-2025" },
      { label: "IEA Energy and AI 更新", url: "https://www.iea.org/news/data-centre-electricity-use-surged-in-2025-even-with-tightening-bottlenecks-driving-a-scramble-for-solutions" },
      { label: "CBRE 2026 数据中心展望", url: "https://www.cbre.com/insights/books/us-real-estate-market-outlook-2026/data-centers" },
    ],
  },
  ai_cloud_backlog: {
    status: "mixed-proxy",
    updatedAt: "2026-05-01",
    cadence: "季度财报",
    headline: {
      label: "Microsoft 商业 RPO",
      value: "$627B",
      subvalue: "FY26 Q3 commercial remaining performance obligation",
      tone: "up",
    },
    delta: {
      label: "Alphabet Cloud backlog",
      value: ">$460B",
      tone: "up",
    },
    chart: {
      type: "bar",
      title: "AI 云需求消化代理",
      unit: "十亿美元",
      items: [
        { label: "Microsoft 商业 RPO", value: 627, displayValue: "$627B", tone: "high" },
        { label: "Alphabet Cloud backlog", value: 460, displayValue: ">$460B", tone: "high" },
        { label: "Microsoft Cloud 收入", value: 54.5, displayValue: "$54.5B", tone: "mid" },
        { label: "AWS 收入", value: 37.6, displayValue: "$37.6B", tone: "mid" },
        { label: "Google Cloud 收入", value: 20.028, displayValue: "$20.0B", tone: "mid" },
        { label: "Baidu AI Cloud Infra FY25", value: 2.75, displayValue: "RMB19.8B", tone: "low" },
      ],
    },
    rows: [
      { label: "Microsoft", value: "FY26 Q3 Microsoft Cloud 收入 $54.5B；商业 RPO $627B；Azure +40%。" },
      { label: "Alphabet", value: "Q1 2026 Google Cloud 收入 $20.0B，同比增长 63%；backlog 环比近翻倍至 >$460B。" },
      { label: "Amazon", value: "Q1 2026 AWS 收入 $37.6B；Trainium AI 芯片相关 backlog 被市场报道为显著增长点。" },
      { label: "Baidu", value: "FY2025 AI Cloud Infra 收入 RMB19.8B，同比增长 34%；Q4 为 RMB5.8B。" },
    ],
    sourceNote: "这是需求吸收代理。RPO、backlog、云收入和 AI Cloud Infra 收入不是同一口径，只能交叉验证 capex 是否被需求吸收。",
    sources: [
      { label: "Microsoft FY26 Q3 指标", url: "https://www.microsoft.com/en-us/investor/earnings/fy-2026-q3/metrics" },
      { label: "Microsoft FY26 Q3 智能云", url: "https://www.microsoft.com/en-us/Investor/earnings/FY-2026-Q3/intelligent-cloud-performance" },
      { label: "Alphabet Q1 2026 SEC 附件", url: "https://www.sec.gov/Archives/edgar/data/1652044/000165204426000043/googexhibit991q12026.htm" },
      { label: "Amazon Q1 2026 业绩", url: "https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-First-Quarter-Results/default.aspx" },
      { label: "Baidu FY2025 业绩", url: "https://ir.baidu.com/news-releases/news-release-details/baidu-announces-fourth-quarter-and-fiscal-year-2025-results" },
    ],
  },
  value_capture: {
    status: "mixed-proxy",
    updatedAt: "2026-05-01",
    cadence: "季度财报 + 事件触发",
    headline: {
      label: "CoreWeave backlog",
      value: "$66.8B",
      subvalue: "AI 云租赁商需求锁定代理",
      tone: "up",
    },
    delta: {
      label: "Broadcom 调整后 EBITDA 率",
      value: "68%",
      tone: "up",
    },
    chart: {
      type: "bar",
      title: "价值捕获代理",
      unit: "十亿美元 / %",
      items: [
        { label: "CoreWeave backlog", value: 66.8, displayValue: "$66.8B", tone: "high" },
        { label: "Broadcom 调整后 EBITDA 率", value: 68, displayValue: "68%", tone: "high" },
        { label: "GDS 利用率", value: 75.5, displayValue: "75.5%", tone: "mid" },
        { label: "Marvell 数据中心占比", value: 74, displayValue: "74%", tone: "mid" },
        { label: "Micron FY26 Q2 经营现金流", value: 11.9, displayValue: "$11.9B", tone: "mid" },
      ],
    },
    rows: [
      { label: "CoreWeave", value: "2025 年末 revenue backlog $66.8B；FY2025 调整后 EBITDA $3.093B，率 60%。" },
      { label: "Broadcom", value: "Q4 FY25 调整后 EBITDA $12.218B，占收入 68%；AI 半导体同比 +74%。" },
      { label: "GDS", value: "Q4 2025 利用率 75.5%，面积利用同比 +11.4%；公用事业成本拖累毛利率。" },
      { label: "Micron", value: "FY26 Q2 经营现金流 $11.90B，体现 AI 内存周期中的现金转化。" },
    ],
    sourceNote: "这是价值捕获代理卡。backlog、EBITDA 率、利用率和现金流不能直接比较；它们回答的是谁把紧缺转成订单、利润率和现金。",
    sources: [
      { label: "CoreWeave FY2025 业绩", url: "https://investors.coreweave.com/news/news-details/2026/CoreWeave-Reports-Strong-Fourth-Quarter-and-Fiscal-Year-2025-Results" },
      { label: "Broadcom FY25 Q4 业绩", url: "https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-fourth-quarter-and-fiscal-year-2025" },
      { label: "GDS FY2025 业绩", url: "https://investors.gds-services.com/news-releases/news-release-details/gds-holdings-limited-reports-fourth-quarter-and-full-year-2025" },
      { label: "Micron FY26 Q2 业绩", url: "https://investors.micron.com/news-releases/news-release-details/micron-technology-inc-reports-results-second-quarter-fiscal-2026" },
      { label: "Marvell FY26 Q4 业绩", url: "https://investor.marvell.com/news-events/press-releases/detail/1011/marvell-technology-inc-reports-fourth-quarter-and-fiscal-year-2026-financial-results" },
    ],
  },
};
